### ISSUE TITLE
chore: add github action workflow to automate release and package publish

### ISSUE THREAD

**Issue by binodnepali** [binodnepali/react-nepali-datetime-picker#17]
Currently release and package publish are done manually. It would be nice automate the process using github action workflow

**Comment by aj3sh** [comment]
I want to contribute to this. Can we use `release-please`?

**Comment by binodnepali** [comment]
Hey @aj3sh Thanks for your interest to contribute. I would go for [commit-and-tag-version](https://github.com/absolute-version/commit-and-tag-version) which forked version of standard version. Let me your thoughts on it :)

**Comment by aj3sh** [comment]
Sure @binodnepali, I will take a deep dive into the [commit-and-tag-version](https://github.com/absolute-version/commit-and-tag-version) documentation. I don't see a direct implementation for using it with GitHub Actions. Even they are using release-please for their releases 😆.

In the meantime, if anyone is interested in this issue, please feel free to proceed.

**Comment by binodnepali** [comment]
@aj3sh I saw you guys using release-please in node-datetime package. if you would like to proceed with release-please. I am fine with it as well :)

**Comment by aj3sh** [comment]
@binodnepali, Let's try commit-and-tag-version first.

**Comment by aj3sh** [comment]
I am able to create releases from commit-and-tag-version through GitHub Actions. I have a question about which event should trigger the release.

**Manual Dispatch**
- Users manually run the release workflow from the GitHub UI.
- A release and tag are created.
- A release PR is generated.

**Git Tag Push**
- A user pushes a version tag (Version should be specified).
- The tag is deleted, and a new tag is created using commit-and-tag-version.
- A release is created.
- A release PR is generated.

**Main Branch Push**
- This method cannot be used due to recursive action triggers on release PR merge.

My recommendation is to use Manual Dispatch. Whenever we feel a release is necessary we trigger the release action manually.

cc: @binodnepali

**Comment by binodnepali** [comment]
> I am able to create releases from commit-and-tag-version through GitHub Actions. I have a question about which event should trigger the release.
> 
> **Manual Dispatch**
> 
> * Users manually run the release workflow from the GitHub UI.
> * A release and tag are created.
> * A release PR is generated.
> 
> **Git Tag Push**
> 
> * A user pushes a version tag (Version should be specified).
> * The tag is deleted, and a new tag is created using commit-and-tag-version.
> * A release is created.
> * A release PR is generated.
> 
> **Main Branch Push**
> 
> * This method cannot be used due to recursive action triggers on release PR merge.
> 
> My recommendation is to use Manual Dispatch. Whenever we feel a release is necessary we trigger the release action manually.
> 
> cc: @binodnepali

Thanks for trying out and providing summary. If you have time, can you open PR with setup? I have look into it.

**Comment by aj3sh** [comment]
@binodnepali, sorry for the late response. I've been a bit busy lately.

I have created a draft PR. Please review it.
